name: chipfit
description: "ChipmunkStudio DesignSystem"
publish_to: 'none'
version: 1.0.0
homepage: https://github.com/chipmunk-studio/chipmunk-fit

environment:
  sdk: ^3.5.3

workspace:
  - component
  - foundation
  - module
  - chip_assets
  - dependencies
  - catalog

dependencies:
  flutter:
    sdk: flutter
  chip_assets:
    path: ./chip_assets
  foundation:
    path: ./foundation
  component:
    path: ./component
  module:
    path: ./module
  dependencies:
    path: ./dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  melos: ^7.1.0

melos:
  scripts:
    get:
      run: melos exec --concurrency=1 -- "flutter pub get"
      description: Run "flutter pub get" in all packages.

    build:
      run: melos exec --depends-on="build_runner" --concurrency=10 -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner for all packages that have it as a dependency.

    build:all:
      run: melos exec --concurrency=10 -- "dart run build_runner build --delete-conflicting-outputs" || true
      description: Run build_runner for all packages including those with build_runner in dev_dependencies.

    build:component:
      run: melos exec --scope="component" -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in the component module.

    build:foundation:
      run: melos exec --scope="foundation" -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in the foundation module.

    build:module:
      run: melos exec --scope="module" -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in the module module.

    build:assets:
      run: melos exec --scope="chip_assets" -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in the chip_assets module.

    build:catalog:
      run: melos exec --scope="catalog" -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in the catalog module.

    clean:
      run: melos exec -- "flutter clean"
      description: Run "flutter clean" in all packages.

    test:
      run: melos exec -- "flutter test"
      description: Run "flutter test" in all packages.

    lint:
      run: melos exec -- "flutter analyze"
      description: Run lint analysis on all packages.

    lint:error:
      run: melos exec -- "flutter analyze --fatal-infos"
      description: Run lint analysis and fail on any issues.

    lint:fix:
      run: melos exec -- "dart fix --apply"
      description: Automatically fix lint issues where possible.

    lint:component:
      run: melos exec --scope="component" -- "flutter analyze"
      description: Run lint analysis on component package.

    lint:foundation:
      run: melos exec --scope="foundation" -- "flutter analyze"
      description: Run lint analysis on foundation package.

    lint:module:
      run: melos exec --scope="module" -- "flutter analyze"
      description: Run lint analysis on module package.

    gen:
      run: melos exec --scope="chip_assets" -- "fluttergen -c pubspec.yaml"
      description: Run flutter_gen for chip_assets module.

    build:main:
      run: dart run build_runner build --delete-conflicting-outputs
      description: Run build_runner in the main app for .g.dart and .freezed.dart files.