name: chipfit
description: "ChipmunkStudio DesignSystem"
version: 1.0.0
homepage: https://github.com/chipmunk-studio/chipmunk-fit

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog:
  flutter_screenutil:
  dartz:
  flutter_cache_manager:
  cached_network_image:
  flutter_animate:
  lottie:
  dotlottie_loader:
  flutter_svg:
  flutter_bounceable:
  flutter_quill:
  sprung:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  lineLength: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Pretendard-Light
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
    - family: Neodgm
      fonts:
        - asset: assets/fonts/neodgm.ttf
          weight: 400