name: module
description: A new Flutter package.
publish_to: 'none'

environment:
  sdk: '^3.5.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  assets:
    path: ../assets
  foundation:
    path: ../foundation
  component:
    path: ../component
  dependencies:
    path: ../dependencies
  flutter_screenutil:
  flutter_bounceable:
  awesome_dialog:
  modal_bottom_sheet:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: