name: foundation
description: A new Flutter package.
publish_to: 'none'

environment:
  sdk: '^3.5.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  chip_assets:
    path: ../chip_assets
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: