name: component
description: A new Flutter package.
publish_to: 'none'

environment:
  sdk: '^3.5.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  assets:
    path: ../assets
  foundation:
    path: ../foundation
  dependencies:
    path: ../dependencies
  dartz:
  flutter_cache_manager:
  cached_network_image:
  flutter_animate:
  lottie:
  dotlottie_loader:
  flutter_svg:
  flutter_bounceable:
  flutter_quill:
  sprung:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: